# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a3e0a281d140b5c85a7b424dae3c4dae8d62c2e9a90d15066676a4b7dd3bf068a95a17abc84fada29a1d97d6e88955826910188241441719c1fb626d7a9ea34

test:
  secret_key_base: 0ce6e9a319da80bf8e8918f1a45c51f2a4ef3243a999945a1579745a9106054f8d9141a8149e348c84668cae745bb4a7f8f93f3c4f938163de7eb8421e22609f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
